version: '2'
services:
    article-app:
        image: article
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://article-mysql:3306/article?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=article-elasticsearch:9300
        ports:
            - 8080:8080
    article-mysql:
        extends:
            file: mysql.yml
            service: article-mysql
    article-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: article-elasticsearch
